# Generated by Django 3.0.5 on 2020-05-12 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=264, unique=True)),
                ('description', models.TextField(blank=True)),
                ('best_before', models.IntegerField(blank=True, default=10)),
                ('category', models.CharField(choices=[('Groceries', 'Groceries'), ('Medicines', 'Medicines'), ('Fruits', 'Fruits'), ('Vegetables', 'Vegetables'), ('Documents', 'Documents'), ('Other', 'Other')], default='Other', max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_no', models.CharField(blank=True, max_length=10, null=True)),
                ('notify_by', models.CharField(choices=[('MAIL', 'Mail'), ('TEXT', 'Text')], default='MAIL', max_length=264)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='ProductExpiryNotification/profile_pics')),
                ('bought', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='bought_by', to='ProductExpiryNotification.Product')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
