# Generated by Django 3.0.5 on 2020-05-12 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductExpiryNotification', '0002_auto_20200513_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='manufactured_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='notification_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
