# Generated by Django 3.0.5 on 2020-05-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductExpiryNotification', '0003_auto_20200513_0134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bought',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bought',
            field=models.ManyToManyField(blank=True, null=True, related_name='bought_by', to='ProductExpiryNotification.Product'),
        ),
    ]
