# Generated by Django 3.0.6 on 2020-05-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductExpiryNotification', '0004_auto_20200513_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Beverages', 'Beverages'), ('Documents', 'Documents'), ('Fruits', 'Fruits'), ('Groceries', 'Groceries'), ('Medicines', 'Medicines'), ('Vegetables', 'Vegetables'), ('Other', 'Other')], default='Other', max_length=264),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bought',
            field=models.ManyToManyField(blank=True, related_name='bought_by', to='ProductExpiryNotification.Product'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notify_by',
            field=models.CharField(choices=[('MAIL', 'Mail'), ('TEXT', 'Text')], default='MAIL', max_length=10),
        ),
    ]
